// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edyfcktyijeedrbbqfgb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkeWZja3R5aWplZWRyYmJxZmdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNjIyNTUsImV4cCI6MjA3MTgzODI1NX0.2T5MvyU21NOdnBdRvXO3N3yHbszSdpylqyRsNptGIQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});